language: ruby
cache: bundler

install:
- bundle install

script:
- bundle exec rake site:deploy --quiet

branches:
  only:
  - master

rvm:
- 2.4.2

env:
  global:
  - secure: DxdWcZ3d5xgPwzy0R8sQTbplWGdt2+ibPNVjc4ieyqIBLBKgENOd/3jBFjtRVVpBiyWlczu4TD6tlzDWiIAgvJTnttFT2uHiVCk7WADffXqJmwJK/LT/cAtZxi54wjJWRWYHLfn+5oES0dIbNIK4Ul8Q9a3tfWR+W5aBywaK3zPCDOI8L2oYZN4zqrfLB3cmQcUB4UUmR0y9EBU7PU+7RAU0Sm4ldbB9hkAKhpYhjbZ/GsqgoIf4YHhwg7w5qmRQ1uXW2OKqpQ+zedciN/4hXhpqzZKLk2ckXXDvArBJLnmSndTnozqX+wOOQ2sRrQVRVQJzxLmvm1DTGUv5cLEDnm6mwTBifyI2U3RMFxCwjLstqN7aO0C+Z8bxx9M3+Oe5Wp5XRZUDi97IvSdbgAoJ0NmJsfrUGMT3ULqBvAP2VoNHDM1cxmI2lXAwsb4LNEA6tXfzyz/Pvd5j3aCHDPCvqITFUKfsDdOtYcsP80/0Lsd5Df9yts5GA6IlFLrJbpmdqXHQ9uSc09xrGUd4/VlZJfBG6DiPTjXZvsknBwvRviFTGVxQBYTTJ8PIIju/Qf4m5fcUNOJE0Umm0a4CyayPp8g0agwwWiYmF79YIGlM+kCVeqzdHVhgpdQbHAN+snrdd5tZjOiyiEOOzD1oGVSoiENNzm7TYM7qTcDvkM1EnM4=
